import { DomainResource } from '../domain-resource';
import { Attachment, CodeableConcept, ContactDetail, Identifier, Period, Reference, UsageContext } from '..';
import { RelatedArtifact } from '../relatedartifact';
import { ParameterDefinition } from '../parameterdefinition';
import { DataRequirement } from '../datarequirement';
export declare class Library extends DomainResource {
    resourceType: string;
    url?: string;
    identifier?: Identifier[];
    version?: string;
    name?: string;
    title?: string;
    subtitle?: string;
    status: 'draft' | 'active' | 'retired' | 'unknown';
    experimental?: boolean;
    type: CodeableConcept;
    subjectCodeableConcept?: CodeableConcept;
    subjectReference?: Reference;
    date?: Date;
    publisher?: string;
    contact?: ContactDetail[];
    description?: string;
    useContext?: UsageContext[];
    jurisdiction?: CodeableConcept[];
    purpose?: string;
    usage?: string;
    copyright?: string;
    approvalDate?: Date;
    lastReviewDate?: Date;
    effectivePeriod?: Period;
    topic?: CodeableConcept[];
    author?: ContactDetail[];
    editor?: ContactDetail[];
    reviewer?: ContactDetail[];
    endorser?: ContactDetail[];
    relatedArtifact?: RelatedArtifact[];
    parameter?: ParameterDefinition[];
    dataRequirement?: DataRequirement[];
    content?: Attachment[];
}
